"use client";

import { useState } from "react";
import SummaryCard from "@/components/ai/SummaryCard";
import { deleteAiSummaryAction, updateAiSummaryAction } from "@/lib/actions";
import type { AiSummary } from "@/lib/types";
import { formatDateTime } from "@/lib/utils";
import { ChevronDown, ChevronUp, Clock, MessageSquareText } from "@/components/ui/HeartfulIcon";

// Every AI version generated for one stage, newest first. The newest is open;
// older ones are one click away. Each version shows the notes it came from,
// can be hand-edited, and can be deleted (with an "are you sure?" check) when
// it was generated by mistake. Nothing is ever replaced — generating again
// adds a new version on top.
export default function SummaryVersions({
  clientId,
  summaries,
  onChange,
  heading,
  description,
  cardTitle,
  variant,
}: {
  clientId: string;
  /** Newest first. */
  summaries: AiSummary[];
  onChange: (next: AiSummary[]) => void;
  heading: string;
  description?: string;
  cardTitle: string;
  variant?: "assessment" | "journey" | "analysis";
}) {
  const [expanded, setExpanded] = useState<string | null>(summaries[0]?.id ?? null);
  const [openedNewest, setOpenedNewest] = useState(summaries[0]?.id);
  const [error, setError] = useState<string | null>(null);

  // A freshly generated version arrives at the top — open it automatically.
  if (summaries[0]?.id !== openedNewest) {
    setOpenedNewest(summaries[0]?.id);
    setExpanded(summaries[0]?.id ?? null);
  }

  if (summaries.length === 0) return null;

  async function remove(summary: AiSummary, versionLabel: string) {
    if (!window.confirm(`Delete ${versionLabel} (${formatDateTime(summary.created_at)})? This can't be undone. Your notes are not affected.`)) return;
    setError(null);
    try {
      await deleteAiSummaryAction(summary.id, clientId);
      onChange(summaries.filter((s) => s.id !== summary.id));
    } catch {
      setError("That version couldn't be deleted — check your connection and try again.");
    }
  }

  async function save(summary: AiSummary, content: Record<string, unknown>) {
    await updateAiSummaryAction(summary.id, clientId, content);
    onChange(summaries.map((s) => (s.id === summary.id ? { ...s, content } : s)));
  }

  const total = summaries.length;

  return (
    <div className="card p-4 space-y-3">
      <h3 className="session-panel-heading flex items-center gap-3">
        <MessageSquareText className="h-4 w-4" aria-hidden="true" />
        {heading}
        {total > 1 && <span className="text-xs font-normal text-ink-400">{total} versions</span>}
      </h3>
      {description && <p className="text-xs text-ink-400">{description}</p>}
      {error && <p role="alert" className="text-xs text-red-600">{error}</p>}
      <div className="space-y-2">
        {summaries.map((summary, index) => {
          const number = total - index;
          const versionLabel = total > 1 ? `version ${number}` : "this version";
          const isOpen = expanded === summary.id;
          return (
            <div key={summary.id} className="summary-version">
              <button
                type="button"
                onClick={() => setExpanded(isOpen ? null : summary.id)}
                aria-expanded={isOpen}
                aria-controls={`summary-version-${summary.id}`}
                className="flex w-full items-center gap-2 py-1 text-left text-sm text-ink-500 hover:text-ink-800"
              >
                <Clock className="h-3.5 w-3.5 shrink-0" aria-hidden="true" />
                <span>
                  {total > 1 ? `Version ${number}` : cardTitle} — {formatDateTime(summary.created_at)}
                  {index === 0 && total > 1 && <span className="badge ml-2 bg-sage-100 text-sage-700">Latest</span>}
                </span>
                {isOpen ? (
                  <ChevronUp className="ml-auto h-4 w-4 shrink-0" aria-hidden="true" />
                ) : (
                  <ChevronDown className="ml-auto h-4 w-4 shrink-0" aria-hidden="true" />
                )}
              </button>
              {isOpen && (
                <div id={`summary-version-${summary.id}`} className="mt-2">
                  <SummaryCard
                    title={cardTitle}
                    content={summary.content}
                    model={summary.model}
                    variant={variant}
                    sourceNotes={summary.source_notes}
                    onDelete={() => remove(summary, versionLabel)}
                    onSave={(next) => save(summary, next)}
                  />
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}
